###
### Mount disk
###

# confirm fstab mounts are created before continuing
sudo mount -a

# mount influxdb volume if it is not already mounted
if [ ! -d "/mnt/influxdb" ]; then
  format_and_mount_disk "influxdb" "/mnt/influxdb"
fi

###
### Set IP address as runtime config
###

readonly ACCESS_TOKEN=$(get_access_token)
readonly PROJECT_ID=$(get_project_id)
readonly EXTERNAL_IP=$(get_external_ip)
readonly INTERNAL_IP=$(get_internal_ip)
readonly NODE_PRIVATE_DNS=$(get_hostname)

readonly DEPLOYMENT=$(get_attribute_value "deployment")
readonly CONFIG=$(get_attribute_value "rtc-name")

readonly EXTERNAL_IP_VAR_PATH=$(get_attribute_value "external-ip-variable-path")
readonly SUCCESS_STATUS_PATH="$(get_attribute_value "status-success-base-path")/$(hostname)"
readonly FAILURE_STATUS_PATH="$(get_attribute_value "status-failure-base-path")/$(hostname)"

readonly LICENSE_KEY=$(get_attribute_value "license-key")

sudo mv /etc/influxdb/influxdb-meta.conf /etc/influxdb/influxdb-meta.conf.backup
echo "# this config was generated by the instance template startup script

hostname = \"${NODE_PRIVATE_DNS}\"

[enterprise]
  license-key = \"${LICENSE_KEY}\"
" | sudo tee -a /etc/influxdb/influxdb-meta.conf > /dev/null

sudo systemctl enable influxdb-meta
sudo systemctl start influxdb-meta

# gcloud beta runtime-config configs variables set meta-dns "${NODE_PRIVATE_DNS}" --config-name "${DEPLOYMENT}-rtc"

set_rtc_var_text "${DEPLOYMENT}-rtc" "internal-dns/meta/${HOSTNAME}" "${NODE_PRIVATE_DNS}"

wait_for_rtc_waiter_success "${DEPLOYMENT}-rtc" "${DEPLOYMENT}-rtc-cluster-init-waiter" "250"

readonly META_LEADER="$(filter_rtc_var "${DEPLOYMENT}-rtc" "internal-dns/meta/" | head -n 1)"

if [ "${HOSTNAME}" != "${META_LEADER}" ]; then
  exit
fi

filter_rtc_var "${DEPLOYMENT}-rtc" "internal-dns/meta/" | while read line; do
  influxd-ctl add-meta $(get_rtc_var_text "${DEPLOYMENT}-rtc" "internal-dns/meta/${line}"):8091
done

filter_rtc_var "${DEPLOYMENT}-rtc" "internal-dns/data/" | while read line; do
  influxd-ctl add-data $(get_rtc_var_text "${DEPLOYMENT}-rtc" "internal-dns/data/${line}"):8088
done

set_rtc_var_text "${DEPLOYMENT}-rtc" "startup-success" "success"
