###
### Mount disk
###

# confirm fstab mounts are created before continuing
sudo mount -a

# mount influxdb volume if it is not already mounted
if [ ! -d "/mnt/influxdb" ]; then
  format_and_mount_disk "influxdb" "/mnt/influxdb"
fi

###
### Set IP address as runtime config
###

readonly ACCESS_TOKEN=$(get_access_token)
readonly PROJECT_ID=$(get_project_id)
readonly EXTERNAL_IP=$(get_external_ip)
readonly INTERNAL_IP=$(get_internal_ip)
readonly NODE_PRIVATE_DNS=$(get_hostname)

readonly DEPLOYMENT=$(get_attribute_value "deployment")
readonly CONFIG=$(get_attribute_value "rtc-name")

readonly EXTERNAL_IP_VAR_PATH=$(get_attribute_value "external-ip-variable-path")
readonly SUCCESS_STATUS_PATH="$(get_attribute_value "status-success-base-path")/$(hostname)"
readonly FAILURE_STATUS_PATH="$(get_attribute_value "status-failure-base-path")/$(hostname)"

readonly LICENSE_KEY=$(get_attribute_value "license-key")

sudo mv /etc/influxdb/influxdb.conf /etc/influxdb/influxdb.conf.backup
echo "# this config was generated by the instance template startup script

hostname = \"${NODE_PRIVATE_DNS}\"

[enterprise]
  license-key = \"${LICENSE_KEY}\"
" sudo tee -a /etc/influxdb/influxdb.conf > /dev/null

sudo systemctl enable influxdb
sudo systemctl start influxdb

set_rtc_var_text "${DEPLOYMENT}-rtc" "internal-dns/data/${HOSTNAME}" "${NODE_PRIVATE_DNS}"
